networking:
  is_networked: False
  is_server: False
  server_ip: ""

voice:
  energy_threshold: 100
  timeout: 3
  phrase_time_limit: 10
  adjust_for_ambient_noise: false

intercom:
  activation_keywords:
    "en_US" : [ "intercom" ]
    "he_IL" : [ "אינטרקום" ]

  "prompt_language_map":
    "he_IL": "Hebrew"
    "en_US": "English"

  prompt_prepend: "Your name is Intercom. You are an AI assistant, similar to Jarvis."

  default_language: "he_IL"

tts:
  use_gpu: True

  "gtts_language_map":
    "he_IL": "iw"
    "en_US": "en"

log_level: "INFO"
