networking:
  is_networked: False
  is_server: False
  server_ip: ""

voice:
  energy_threshold: 100
  timeout: 3
  phrase_time_limit: 10
  adjust_for_ambient_noise: false

intercom:
  activation_keywords:
    "en_US" : [ "intercom" ]
    "he_IL" : [ "אינטרקום" ]

  "prompt_language_map":
    "he_IL": "Hebrew"
    "en_US": "English"

  default_language: "he_IL"

tts:
  "gtts_language_map":
    "he_IL": "iw"
    "en_US": "en"

ai:
  type: "Gemini"
  conversation_starter: "Your name is Intercom. You are an AI assistant, similar to Jarvis. Only speak in human understandable words and avoid formatting, code, etc. Answer in a short and concise way."

log_level: "INFO"
