name: py-intercom

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip=24
  - gTTS=2.5
  - openai=1.13
  - speechrecognition=3.10.1
  - PyAudio=0.2
  - pyyaml=6.0.1
  - plac=1.4.3
  - pygobject==3.46.0

  - pip:
    - playsound==1.3.0
    - piney-event==0.0.2
